import { credentialResolverSnippet, telemetrySendSnippet } from './resolve-credentials.sh.js';

export function generateClaudeSlashCommandHook(baseUrl: string): string {
  return `#!/bin/bash
# aictrl slash-command telemetry hook for Claude Code (UserPromptSubmit)
# Auto-generated by @aictrl/plugin — do not edit manually
#
# Workaround for anthropics/claude-code#38915: slash commands like
# /skill-name bypass the tool pipeline so PostToolUse hooks never fire.
# Parse the prompt, validate the command name exists locally as a skill
# or command, and post telemetry with source="claude-code-slash".

set -eo pipefail

INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // empty' 2>/dev/null)
[ -z "$PROMPT" ] && exit 0

${credentialResolverSnippet(baseUrl)}

# Extract leading slash command from FIRST line only.
# Matches /name or plugin-prefixed /plugin:name forms.
COMMAND=$(echo "$PROMPT" | head -n1 | grep -oE '^/[a-z0-9][a-z0-9:_-]*' | head -n1 || true)
COMMAND="\${COMMAND#/}"
[ -z "$COMMAND" ] && exit 0

# Keep qualified name for telemetry; strip plugin prefix for filesystem lookup.
QUALIFIED_NAME="$COMMAND"
BARE_NAME="\${COMMAND##*:}"

# Validate the skill/command exists locally before sending telemetry.
FOUND=0
for path in \\
  "$HOME/.claude/skills/$BARE_NAME/SKILL.md" \\
  "$PROJECT_ROOT/.claude/skills/$BARE_NAME/SKILL.md" \\
  "$PROJECT_ROOT/.claude/commands/$BARE_NAME.md"; do
  if [ -f "$path" ]; then FOUND=1; break; fi
done

# Plugin cache paths can be 4+ levels deep
# (e.g. ~/.claude/plugins/cache/<marketplace>/<plugin>/<version>/skills/<name>/SKILL.md).
# Use depth-bounded find rather than glob.
if [ "$FOUND" -eq 0 ] && [ -d "$HOME/.claude/plugins/cache" ]; then
  if find "$HOME/.claude/plugins/cache" -maxdepth 6 -type f \\
      \\( -path "*/skills/$BARE_NAME/SKILL.md" -o -path "*/commands/$BARE_NAME.md" \\) \\
      -print -quit 2>/dev/null | grep -q .; then
    FOUND=1
  fi
fi

[ "$FOUND" -eq 0 ] && exit 0

${telemetrySendSnippet()}

send_telemetry "$QUALIFIED_NAME" "claude-code-slash"
`;
}
