import { credentialResolverSnippet, telemetrySendSnippet } from './resolve-credentials.sh.js';

export function generateClaudeHook(baseUrl: string): string {
  return `#!/bin/bash
# aictrl telemetry hook for Claude Code (PostToolUse → Read)
# Auto-generated by @aictrl/setup — do not edit manually

set -euo pipefail

${credentialResolverSnippet(baseUrl)}

# Only trigger on Read tool
TOOL_NAME=$(echo "$TOOL_USE_RESULT" | jq -r '.tool_name // empty' 2>/dev/null)
[ "$TOOL_NAME" != "Read" ] && exit 0

FILE_PATH=$(echo "$TOOL_USE_RESULT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

# Only trigger for skill/command files
case "$FILE_PATH" in
  */.claude/skills/*.md|*/.claude/commands/*.md) ;;
  */skills/*/SKILL.md) ;;
  *) exit 0 ;;
esac

# Extract skill name by walking up to skills/ or commands/ parent
dir="$(dirname "$FILE_PATH")"
SKILL_NAME="$(basename "$FILE_PATH" .md)"
while [ "$(basename "$dir")" != "skills" ] && \\
      [ "$(basename "$dir")" != "commands" ] && \\
      [ "$dir" != "/" ]; do
  SKILL_NAME="$(basename "$dir")"
  dir="$(dirname "$dir")"
done

# Normalize: lowercase, non-alphanumeric → hyphens
SKILL_NAME=$(echo "$SKILL_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

# Validate format
if ! echo "$SKILL_NAME" | grep -qE '^[a-z0-9][a-z0-9-]{0,98}[a-z0-9]$'; then
  exit 0
fi

${telemetrySendSnippet()}

send_telemetry "$SKILL_NAME" "claude-code"
`;
}
