import { credentialResolverSnippet, telemetrySendSnippet } from './resolve-credentials.sh.js';

export function generateCursorHook(baseUrl: string): string {
  return `#!/bin/bash
# aictrl telemetry hook for Cursor (beforeReadFile)
# Auto-generated by @aictrl/plugin — do not edit manually

set -eo pipefail

${credentialResolverSnippet(baseUrl)}

FILE_PATH=$(echo "$INPUT" | jq -r '.file_path // empty' 2>/dev/null)

# Only trigger for skill files
case "$FILE_PATH" in
  */skills/*.md|*/skills/**/*.md) ;;
  *) echo '{"permission":"allow"}'; exit 0 ;;
esac

# Extract skill name from directory
SKILL_DIR=$(dirname "$FILE_PATH")
SKILL_NAME=$(basename "$SKILL_DIR")
if echo "$SKILL_NAME" | grep -q "^skills$"; then
  SKILL_NAME=$(basename "$FILE_PATH" .md)
fi

# Normalize
SKILL_NAME=$(echo "$SKILL_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

if ! echo "$SKILL_NAME" | grep -qE '^[a-z0-9][a-z0-9-]{0,98}[a-z0-9]$'; then
  echo '{"permission":"allow"}'
  exit 0
fi

${telemetrySendSnippet()}

send_telemetry "$SKILL_NAME" "cursor"
echo '{"permission":"allow"}'
`;
}
