import { credentialResolverSnippet, telemetrySendSnippet } from './resolve-credentials.sh.js';

export function generateOpenCodeHook(baseUrl: string): string {
  return `#!/bin/bash
# aictrl telemetry hook for OpenCode (skill tool invocation)
# Auto-generated by @aictrl/setup — do not edit manually

set -euo pipefail

${credentialResolverSnippet(baseUrl)}

# Only trigger on skill tool
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null)
[ "$TOOL_NAME" != "skill" ] && exit 0

SKILL_NAME=$(echo "$INPUT" | jq -r '.tool_input.name // empty' 2>/dev/null)
[ -z "$SKILL_NAME" ] && exit 0

# Normalize
SKILL_NAME=$(echo "$SKILL_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

if ! echo "$SKILL_NAME" | grep -qE '^[a-z0-9][a-z0-9-]{0,98}[a-z0-9]$'; then
  exit 0
fi

${telemetrySendSnippet()}

send_telemetry "$SKILL_NAME" "opencode"
`;
}
